# Generated by Django 6.1 on 2026-10-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('Select_User', models.CharField(choices=[('Super Admin', 'Super Admin'), ('Admin', 'Admin'), ('DOCTOR', 'Doctor'), ('NURSES', 'Nurses'), ('RECEPTIONISTS', 'Receptionists'), ('PATIENTS', 'Patients')], max_length=20)),
            ],
        ),
    ]
