# Generated by Django 6.1 on 2026-09-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_Management_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='Select_User',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('NURSES', 'Nurses'), ('RECEPTIONISTS', 'Receptionists'), ('PATIENTS', 'Patients')], max_length=20),
        ),
    ]
