# Generated by Django 6.1 on 2026-10-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_Name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
