# Generated by Django 6.1 on 2026-09-18 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hospitals',
        ),
    ]
