# Generated by Django 6.1 on 2026-09-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Super_Admin', '0002_delete_hospitals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('Branch_Code', models.CharField(blank=True, max_length=50, unique=True)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
