# Generated by Django 6.1 on 2026-10-07 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0002_remove_appointment_patient_appointment_patient_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='consultation_fee',
        ),
    ]
