# Generated by Django 6.1 on 2026-10-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0003_remove_appointment_consultation_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='contact',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
