# Generated by Django 6.1 on 2026-09-21 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField()),
                ('created', models.DateField(auto_now_add=True)),
                ('Hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Super_Admin.hospitals')),
            ],
        ),
    ]
