# Generated by Django 6.1 on 2026-10-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0004_appointment_contact_appointment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='age',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
