# Generated by Django 6.1 on 2026-09-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0004_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitals',
            name='ambulances_count',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='hospitals',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hospitals',
            name='established_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hospitals',
            name='icu_beds',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='hospitals',
            name='license_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hospitals',
            name='nicu_beds',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='hospitals',
            name='operation_theatres',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='hospitals',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitals',
            name='pharmacy',
            field=models.CharField(default='24x7 In-House Pharmacy', max_length=100),
        ),
        migrations.AddField(
            model_name='hospitals',
            name='registration_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hospitals',
            name='total_beds',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='hospitals',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='contact',
            field=models.CharField(max_length=20),
        ),
    ]
