# Generated by Django 6.1 on 2026-10-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0005_appointment_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
