# Generated by Django 6.1 on 2026-09-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0005_hospitals_ambulances_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitals',
            name='ambulances_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='icu_beds',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='nicu_beds',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='operation_theatres',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='total_beds',
            field=models.IntegerField(),
        ),
    ]
