# Generated by Django 6.1 on 2026-10-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0006_appointment_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Appoment_id',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
