# Generated by Django 6.1 on 2026-10-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0007_appointment_appoment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Appoment_id',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='role',
            field=models.CharField(blank=True, choices=[('Front Desk Receptionist', 'Front Desk Receptionist'), ('Patient Registration Receptionist', 'Patient Registration Receptionist'), ('Appointment Receptionist', 'Appointment Receptionist'), ('Admission Receptionist', 'Admission Receptionist'), ('Billing Receptionist', 'Billing Receptionist'), ('Emergency Receptionist', 'Emergency Receptionist')], max_length=100, null=True),
        ),
    ]
