# Generated by Django 6.1 on 2026-09-21 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0008_alter_hospitaladmin_hospital_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nurse_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('role', models.CharField(default='Staff Nurse', max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('shift', models.CharField(max_length=100)),
                ('qualification', models.CharField(blank=True, max_length=150, null=True)),
                ('experience', models.CharField(blank=True, max_length=50, null=True)),
                ('contact', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(default='On Duty', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nurses', to='Super_Admin.hospitals')),
            ],
        ),
    ]
