# Generated by Django 6.1 on 2026-10-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0008_alter_appointment_appoment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='checkup_status',
            field=models.CharField(blank=True, choices=[('Checkup Done', 'Checkup Done'), ('Pending', 'Pending')], null=True),
        ),
    ]
