# Generated by Django 6.1 on 2026-09-21 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0009_nurse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('receptionist_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('role', models.CharField(default='Front Desk Executive', max_length=100)),
                ('desk', models.CharField(max_length=100)),
                ('shift', models.CharField(max_length=100)),
                ('languages', models.CharField(default='English, Hindi', max_length=150)),
                ('extension', models.CharField(blank=True, max_length=20, null=True)),
                ('contact', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receptionists', to='Super_Admin.hospitals')),
            ],
        ),
    ]
