# Generated by Django 6.1 on 2026-10-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0009_appointment_checkup_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], null=True),
        ),
    ]
