# Generated by Django 6.1 on 2026-09-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0011_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaladmin',
            name='password',
            field=models.CharField(default=123456789, max_length=128),
        ),
    ]
