# Generated by Django 6.1 on 2026-09-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0012_hospitaladmin_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='hospital',
        ),
        migrations.AddField(
            model_name='doctor',
            name='additional_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospitals',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='Super_Admin.hospitals'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(default='doctor123', max_length=128),
        ),
    ]
