# Generated by Django 6.1 on 2026-09-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0013_remove_doctor_hospital_doctor_additional_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='hospitaladmin',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
