# Generated by Django 6.1 on 2026-09-22 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0014_alter_doctor_password_alter_hospitaladmin_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='code',
        ),
    ]
