# Generated by Django 6.1 on 2026-09-22 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0015_remove_department_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
