# Generated by Django 6.1 on 2026-09-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0016_delete_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitals',
            name='license_no',
        ),
        migrations.RemoveField(
            model_name='hospitals',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='hospitals',
            name='pharmacy',
        ),
        migrations.RemoveField(
            model_name='hospitals',
            name='registration_no',
        ),
        migrations.RemoveField(
            model_name='hospitals',
            name='website',
        ),
        migrations.AddField(
            model_name='hospitals',
            name='departments',
            field=models.TextField(blank=True, help_text='Enter departments separated by commas (e.g. Cardiology, Neurology, Orthopedics)', null=True),
        ),
        migrations.AddField(
            model_name='hospitals',
            name='restroom_for_relatives',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='Branch_Code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='nicu_beds',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
