# Generated by Django 6.1 on 2026-09-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0017_remove_hospitals_license_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='chamber',
        ),
        migrations.RemoveField(
            model_name='receptionist',
            name='desk',
        ),
        migrations.RemoveField(
            model_name='receptionist',
            name='extension',
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctor_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='password',
            field=models.CharField(default='nurse123', max_length=128),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='password',
            field=models.CharField(default='rec123', max_length=128),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.TextField(blank=True, help_text='Enter departments associated with selected hospitals', null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.TextField(help_text='Enter one or more specializations'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='nurse_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='role',
            field=models.CharField(choices=[('Head Nurse', 'Head Nurse'), ('Staff Nurse', 'Staff Nurse'), ('ICU Nurse', 'ICU Nurse'), ('Emergency Nurse', 'Emergency Nurse'), ('OT Nurse', 'OT Nurse'), ('Ward Nurse', 'Ward Nurse')], default='Staff Nurse', max_length=100),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='ward',
            field=models.CharField(choices=[('ICU', 'ICU'), ('NICU', 'NICU'), ('General Ward', 'General Ward'), ('Emergency Ward', 'Emergency Ward'), ('Operation Theatre', 'Operation Theatre'), ('OPD', 'OPD')], default='General Ward', max_length=100),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='role',
            field=models.CharField(choices=[('Front Desk Receptionist', 'Front Desk Receptionist'), ('Patient Registration Receptionist', 'Patient Registration Receptionist'), ('Appointment Receptionist', 'Appointment Receptionist'), ('Admission Receptionist', 'Admission Receptionist'), ('Billing Receptionist', 'Billing Receptionist'), ('Emergency Receptionist', 'Emergency Receptionist')], default='Front Desk Receptionist', max_length=100),
        ),
    ]
