# Generated by Django 6.1 on 2026-09-22 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0018_remove_doctor_chamber_remove_receptionist_desk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age_gender',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hospital_admin',
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='attached_document',
            field=models.FileField(blank=True, help_text='Upload prescription, photo, or medical PDF report', null=True, upload_to='patient_documents/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(blank=True, help_text='Assigned automatically or by receptionist based on availability', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_appointments', to='Super_Admin.doctor'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Admitted', 'Admitted'), ('Discharged', 'Discharged'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='symptoms_diagnosis',
            field=models.TextField(blank=True, help_text='Patient describes symptoms or illness', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='visit_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
