# Generated by Django 6.1 on 2026-09-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0019_remove_patient_age_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.TextField(blank=True, null=True),
        ),
    ]
