# Generated by Django 6.1 on 2026-09-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0021_remove_doctor_opd_timings_doctor_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='available_days',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='consultation_fee',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='emergency_available',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='joining_date',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='medical_registration_number',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='room_cabin_number',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='start_time',
        ),
        migrations.AddField(
            model_name='doctor',
            name='opd_timings',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.TextField(blank=True, null=True),
        ),
    ]
