# Generated by Django 6.1 on 2026-09-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0022_remove_doctor_address_remove_doctor_available_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
