# Generated by Django 6.1 on 2026-09-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0024_doctor_consultation_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='payment_method',
            field=models.CharField(blank=True, help_text='e.g., Cash, UPI, Credit Card', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Partial', 'Partial'), ('Pending', 'Pending'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
