# Generated by Django 6.1 on 2026-09-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0025_patient_amount_paid_patient_consultation_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Blood_Group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=10, null=True),
        ),
    ]
