# Generated by Django 6.1 on 2026-09-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0026_patient_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='password',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('UPI', 'Upi'), ('CREDIT CARD', 'Credit Card'), ('NET BANKING', 'Net Banking'), ('CASH', 'Cash')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='languages',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
