# Generated by Django 6.1 on 2026-09-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0027_alter_doctor_department_alter_nurse_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('UPI', 'Upi'), ('Credit Card', 'Credit Card'), ('Net Banking', 'Net Banking'), ('Cash', 'Cash')], max_length=50, null=True),
        ),
    ]
