# Generated by Django 6.1 on 2026-09-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0028_alter_patient_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Partial', 'Partial'), ('Pending', 'Pending'), ('Failed', 'Failed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Admitted', 'Admitted'), ('Discharged', 'Discharged'), ('Cancelled', 'Cancelled')], max_length=50),
        ),
    ]
