# Generated by Django 6.1 on 2026-09-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0029_alter_patient_gender_alter_patient_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='role',
            field=models.CharField(choices=[('Head Nurse', 'Head Nurse'), ('Staff Nurse', 'Staff Nurse')], max_length=100),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='ward',
            field=models.CharField(choices=[('ICU', 'ICU'), ('NICU', 'NICU'), ('General Ward', 'General Ward'), ('Emergency Ward', 'Emergency Ward'), ('Operation Theatre', 'Operation Theatre'), ('OPD', 'OPD')], max_length=100),
        ),
    ]
