# Generated by Django 6.1 on 2026-09-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0030_alter_nurse_role_alter_nurse_ward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='hospitals',
            field=models.ManyToManyField(related_name='doctors', to='Super_Admin.hospitals'),
        ),
    ]
