# Generated by Django 6.1 on 2026-09-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0031_alter_doctor_hospitals'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Hospitals_Chargies',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
