# Generated by Django 6.1 on 2026-09-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0032_patient_hospitals_chargies'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Condation',
            field=models.CharField(blank=True, choices=[('Critical', 'Critical'), ('Emergency', 'Emergency'), ('Urgent', 'Urgent'), ('Normal', 'Normal')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='departments',
            field=models.TextField(blank=True, help_text='You Can enter Multy Departments', null=True),
        ),
    ]
