# Generated by Django 6.1 on 2026-09-30 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0033_patient_condation_alter_hospitals_departments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
