# Generated by Django 6.1 on 2026-09-30 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0034_delete_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('patient_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('visit_date_time', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('symptoms_diagnosis', models.TextField(blank=True, help_text='Patient describes symptoms or illness', null=True)),
                ('Blood_Group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=10, null=True)),
                ('attached_document', models.FileField(blank=True, help_text='Upload prescription, photo, or medical PDF report', null=True, upload_to='patient_documents/')),
                ('Hospitals_Chargies', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Partial', 'Partial'), ('Pending', 'Pending'), ('Failed', 'Failed')], max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('UPI', 'Upi'), ('Credit Card', 'Credit Card'), ('Net Banking', 'Net Banking'), ('Cash', 'Cash')], max_length=50, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Admitted', 'Admitted'), ('Discharged', 'Discharged'), ('Cancelled', 'Cancelled')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('Condation', models.CharField(blank=True, choices=[('Critical', 'Critical'), ('Emergency', 'Emergency'), ('Urgent', 'Urgent'), ('Normal', 'Normal')], max_length=40, null=True)),
                ('doctor', models.ForeignKey(blank=True, help_text='Assigned automatically or by receptionist based on availability', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_appointments', to='Super_Admin.doctor')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='Super_Admin.hospitals')),
            ],
        ),
    ]
