# Generated by Django 6.1 on 2026-10-01 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0035_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='bed_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
