# Generated by Django 6.1 on 2026-10-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0036_patient_bed_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='assigned_floor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='max_patient_capacity',
            field=models.IntegerField(default=50),
        ),
    ]
