# Generated by Django 6.1 on 2026-10-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0037_nurse_assigned_floor_nurse_max_patient_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='bed_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
