# Generated by Django 6.1 on 2026-10-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0038_alter_patient_bed_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='bed_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
