# Generated by Django 6.1 on 2026-10-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0039_alter_patient_bed_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='feedback_of_patient',
            field=models.TextField(blank=True, null=True),
        ),
    ]
