# Generated by Django 6.1 on 2026-10-01 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0040_nurse_feedback_of_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurse',
            name='feedback_of_patient',
        ),
    ]
