# Generated by Django 6.1 on 2026-10-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0041_remove_nurse_feedback_of_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='status',
            field=models.CharField(choices=[('On_Duty', 'On_Duty'), ('Off_Duty', 'Off_Duty')], max_length=50),
        ),
    ]
