# Generated by Django 6.1 on 2026-10-03 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0042_alter_nurse_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaladmin',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Super_Admin.hospitals', to_field='Name'),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='Name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
