# Generated by Django 6.1 on 2026-10-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0043_alter_hospitaladmin_hospital_alter_hospitals_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Frist_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Address', models.TextField()),
                ('Age', models.IntegerField(max_length=3)),
                ('Gender', models.CharField(max_length=30)),
                ('Number', models.CharField(max_length=14)),
                ('Disease_Details', models.CharField(max_length=300)),
            ],
        ),
    ]
