# Generated by Django 6.1 on 2026-10-03 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin', '0044_appoiment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appoiment',
        ),
    ]
